#!/bin/bash

remoteName="`remote`"

originName=`LANG=en_GB git branch -vv | sed 's/\* /ACTIVE_BRANCH /' | grep ACTIVE_BRANCH | awk '{ print $4 }' | sed "s/\[$remoteName\/\([a-zA-Z0-9_\.\/-]*\).*/\1/"`

echo $originName
