#!/bin/bash

if [ ! -e .git/config ]
then
    dsay "Not in a git repository root"
    exit
fi


echo ""
echo -e "     \e[31m    DELIVERY INBOUND! \e[32m"
echo "--                              /"
echo "--   !      /-----\============@--        ---==>"
echo "--   |_____/_______\_____       \\"
echo "--  /____________________\\"
echo "--   \*__o__o__o__o__o__*/"
echo "-- "

gerrit="`grep gerrit .git/config`"
#bitbuc="`grep 'bitbucket.pearson.com' .git/config`"
bitbuc=""
refs=""

if [ "$gerrit" == "" ] && [ "$bitbuc" == "" ]
then
  refs=""
else
  refs="use those refs baby"
fi

if [ "$1" == "" ]
then
  BRANCH="`origin`"
else
  BRANCH="$1"
fi

echo -e "\e[33m"
if [ "$refs" == "" ]
then
  LANG=en_GB git push origin HEAD:$BRANCH
else
  LANG=en_GB git push origin HEAD:refs/for/$BRANCH
fi
echo -e "\e[0m"
