#!/bin/bash
dsay "ALL YOUR REBASE ARE BELONG TO US!"
LANG=en_GB git pull --rebase
if [ -e ./symfony ]
then
  LANG=en_GB git submodule foreach git pull --rebase origin master
  ./db up
fi
dsay "UR CODE IZ BETTERZ NOW!"
